
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test_unit:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code  
      uses: actions/checkout@v4
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies    
      run: npm install
    - name: Start application in bg mode  
      run: npm run start &
    - name: Print my username
      run: echo "Konspirat0r is my Softuni username"
    - name: Execute unit tests
      run: npm run test:unit
